### ISSUE TITLE
Support for dxf or svg

### ISSUE THREAD

**Issue by lukilukeskywalker** [ma-ha/kicad-laser-stencil-plugin#2]
Wouldn't it be better it to be able to export as a dxf file or svg file? Some laser cutters might have other gcode flavors or control comands.
Not a Issue, more like a feature support¿?

**Comment by ma-ha** [comment]
Hi! I run into extreme problems* with i.e. SVG files, that's why I developed this plugin. GCode is the native language most laser cutters understand and IMHO quite good standardized. The required command set is very limited, so they should be supported by all Laser Cutters - which support GCode at all ;-). Currently I don't plan to extend it, but feel free to fork it :-)
*) The SVG to GCode plugins e.g. in Inkscape are really buggy and do also funny things, especially with all SVG generation I tried from KiCad, e.g. via PDF, as Screen Shot, via Gerber.
